[versions]
agp = "8.13.0"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
workerver = "2.10.5"
okhttpver = "5.2.1"
gsonver = "2.13.2"
gmsver = "21.3.0"
matver = "1.4.0"
activityCompose = "1.11.0"
composeBom = "2025.10.00"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

# worker
coworker = { module = "androidx.work:work-runtime-ktx", version.ref = "workerver" }
# websocket
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpver" }
# json
gson = { module = "com.google.code.gson:gson", version.ref = "gsonver" }
# location
gms = { module = "com.google.android.gms:play-services-location", version.ref = "gmsver"}
# material3
mater3 = { module = "androidx.compose.material3:material3", version.ref = "matver" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
